sudo: required
services:
  - docker

before_install:
  - docker build -t aware74/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aware74/react-test npm test

after_success:
  - docker build -t aware74/multi-client ./client
  - docker build -t aware74/multi-nginx ./nginx
  - docker build -t aware74/multi-server ./server
  - docker build -t aware74/multi-worker ./worker
  # Log into the Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push aware74/multi-client
  - docker push aware74/multi-nginx
  - docker push aware74/multi-server
  - docker push aware74/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-001565686503Info'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY